export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";

export const LIST_PRODUCTS_REQUEST = "LIST_PRODUCTS_REQUEST";
export const LIST_PRODUCTS_SUCCESS = "LIST_PRODUCTS_SUCCESS";
export const LIST_PRODUCTS_FAIL = "LIST_PRODUCTS_FAIL";

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";

//CLIENT CALLS

export const CLIENT_LIST_PRODUCTS_REQUEST = "CLIENT_LIST_PRODUCTS_REQUEST";
export const CLIENT_LIST_PRODUCTS_SUCCESS = "CLIENT_LIST_PRODUCTS_SUCCESS";
export const CLIENT_LIST_PRODUCTS_FAIL = "CLIENT_LIST_PRODUCTS_FAIL";

export const CLIENT_GET_PRODUCT_DETAILS_REQUEST =
  "CLIENT_GET_PRODUCT_DETAILS_REQUEST";
export const CLIENT_GET_PRODUCT_DETAILS_SUCCESS =
  "CLIENT_GET_PRODUCT_DETAILS_SUCCESS";
export const CLIENT_GET_PRODUCT_DETAILS_FAIL =
  "CLIENT_GET_PRODUCT_DETAILS_FAIL";

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
